name: latest

on:
  push:
    branches:
    - master

jobs:

  latest:
    env:
      image: aws-nlb-helper-operator
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.0'

    - name: Run build
      run: |
        make build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to the container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push to the container registry
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: build/Dockerfile
        tags: ${{ secrets.REGISTRY_SERVER }}/${{ secrets.REGISTRY_NAMESPACE }}/${{ env.image }}:latest
        push: true

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}