name: release

on:

  release:
    types:
      - published

jobs:

  release:
    env:
      image: aws-nlb-helper-operator
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.0'

    - name: Run build
      run: |
        make build

    - name: Run build
      run: |
        make test

    - name: Get image tag
      id: image_tag
      run: |
        echo -n ::set-output name=TAG::
        TAG=latest
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          TAG=${GITHUB_REF#refs/tags/}
        fi
        ( echo "${TAG}" )

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to the container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push to the container registry
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: build/Dockerfile
        tags: ${{ secrets.REGISTRY_SERVER }}/${{ secrets.REGISTRY_NAMESPACE }}/${{ env.image }}:${{ steps.image_tag.outputs.TAG }}
        push: true

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}